### ISSUE TITLE
Security Setting tasks not working for jdk17

### ISSUE THREAD

**Issue by adamerstelle** [Rheinwerk/ansible-role-zulu_jdk#3]
I'm looking to use this role to deploy zulu17, and most of it works well except for the 2 security settings tasks.

```
  - role: rheinwerk.ansible_role_zulu_jdk
    _zulu_jdk:
      apt_repo:
        repo_line: "deb http://repos.azulsystems.com/ubuntu stable main"
        key_id: "0xB1998361219BD9C9"
      package_name: "zulu17"
      install_dir: "/usr/lib/jvm/zulu17"
      security:
        dns_cache_ttl: 30
        dns_cache_negative_ttl: 10
```

I'm thinking that the settings tasks could be re-worked so that the if statement looked for the older JDKs instead of newer ones?

(side note: I'd also love to be able to set just the package name instead of having to set everything else...but this could just be me not being an ansible expert and missing something)
